#include <linux/module.h>
#include <linux/highmem.h>
#include <linux/kallsyms.h>
#include <linux/syscalls.h>
#include <asm/syscall_wrapper.h>
#include <linux/fdtable.h>
#include <linux/sched.h>
#include <linux/kernel.h>
#include <linux/cred.h> 
#include <linux/delay.h>
#include <linux/uaccess.h>
